#pragma once

#define OFXGGML_VISION_VERSION_MAJOR 1
#define OFXGGML_VISION_VERSION_MINOR 0
#define OFXGGML_VISION_VERSION_PATCH 1
#define OFXGGML_VISION_VERSION_STRING "1.0.1"

inline const char * ofxGgmlVisionGetVersionString() {
	return OFXGGML_VISION_VERSION_STRING;
}
